server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=Bholu@620

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (must match gateway secret)
app.security.secret=dev-secret-change-me-use-at-least-32-bytes

services.doctor.url=http://localhost:8082

logging.level.org.springframework.security=INFO

